/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2015-09-18 23:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bl.ventas.*;
import com.el.ventas.*;
import java.util.*;

public final class frmCustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <h3>Registro Customer</h3>\r\n");
      out.write("   ");

                    CustomerEnt c = new CustomerEnt();
					if(request.getParameter("idCustomer")!=null){
						int id = Integer.parseInt(request.getParameter("idCustomer"));
						c = CustomerBL.Instancia().DevuelveCustomer(id);
					}					
	 
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t <form method=\"post\" action=\"sFrmCustomer\">\r\n");
      out.write("    <table border=\"1\">\r\n");
      out.write("    <tr><td>idCustomer:</td><td><input type=\"text\" name=\"txtIdCustomer\" value=\"");
      out.print(c.getIdCustomer() );
      out.write("\" /></td></tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Codigo</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtCodigo\" value=\"");
      out.print(c.getCodigo() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>RazonSocial</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtRazSocial\" value=\"");
      out.print(c.getRazSocial() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Direccion</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtDireccion\" value=\"");
      out.print(c.getDireccion() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td>Telefono</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtTelefono\" value=\"");
      out.print(c.getTelefono() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td>Mail</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtMail\" value=\"");
      out.print(c.getMail() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Tipocte</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"txtTipocte\" value=\"");
      out.print(c.getTipocte() );
      out.write("\"/></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td colspan=\"2\">\r\n");
      out.write("\t\t <input type=\"submit\" name=\"btnGrabar\" value=\"Grabar\"/>\r\n");
      out.write("\t\t <input type=\"submit\" name=\"btnEliminar\" value=\"Eliminar\" ");
if(request.getParameter("idCustomer")==null){out.print("disabled");} 
      out.write(" />\r\n");
      out.write("\t  </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("     ");

	out.print("<p style='color: blue'>"+request.getParameter("msj")+"</p>");
	
      out.write("\r\n");
      out.write("  <br/>\r\n");
      out.write("  <table border=\"1\" style=\"width=100%\">\r\n");
      out.write("      <thead style=\"background-color:yellow\">\r\n");
      out.write("         <tr>\r\n");
      out.write("           <th>Codigo</th>\r\n");
      out.write("           <th>RazonSocial</th>\r\n");
      out.write("           <th>Direccion</th>\r\n");
      out.write("           <th>Telefono</th>\r\n");
      out.write("           <th>Mail</th>\r\n");
      out.write("           <th>Tipocte</th>\r\n");
      out.write("           <th>----</th>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("       <tbody>\r\n");
      out.write("       ");

       try{
         ArrayList<CustomerEnt> lista = CustomerBL.Instancia().ListarCustomer();
         for(int i=0;i<lista.size();i++)
         {
        	 out.print("<tr>");
        	 out.print("<td>"+lista.get(i).getCodigo()+"</td>");
        	 out.print("<td>"+lista.get(i).getRazSocial()+"</td>");
        	 out.print("<td>"+lista.get(i).getDireccion()+"</td>");
        	 out.print("<td>"+lista.get(i).getTelefono()+"</td>");
        	 out.print("<td>"+lista.get(i).getMail()+"</td>");
        	 out.print("<td>"+lista.get(i).getTipocte()+"</td>");
        	 out.print("<td><a href='frmCustomer.jsp?idCustomer="+
						lista.get(i).getIdCustomer()+"'>Editar</a></td>");
        	 out.print("</tr>");
         }
      }catch(Exception e)
       {
    	   out.print("<h3>"+e.getMessage()+"</h3>");
       }
       
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       </tbody>\r\n");
      out.write("  </table>    \r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
